project:
  type: website
  output-dir: docs

website:
  title: "ASA Leiden 2026"
  favicon: imgs/lumc-monogram-blauw-jpg.jpg
  search:
    location: navbar
    type: textbox
  page-footer:
    left: (c) Biomedical Data Sciences (LUMC), 2025 &middot; See [copyright statement](/copyright.qmd)
    center: Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
  navbar:
    pinned: true
    logo: imgs/lumc-monogram-blauw-jpg.jpg
    background: "#22092C"
    foreground: "#F8F8F8"
    left:
      - text: Home
        href: index.qmd
      - text: Course content
        href: about.qmd
      # - text: Schedule
      #   href: resources/schedule.qmd
      - text: Cancellation policy
        href: resources/cancellation.qmd
    right:
      - icon: github
        href: https://github.com/survival-lumc

format:
  html:
    css: styles.css
    theme: cosmo
    toc: true
    title-block-banner: true
