---
title: "Cancellation policy"
---

## Cancellation by the participant

If the participant cancels his or her participation after enrolment the following policy applies:

- Cancellation before December 2, 2025: 100% refund minus &euro;75.00 administration fees
- Cancellation between December 2 and December 19, 2025: 50% refund
- Cancellation on or after December 19, 2025: no refund

## Force majeure

Whilst every attempt is made to ensure that the course is run as advertised, LUMC reserves the right to cancel the course due to:

- Circumstances outside its control, including, but not limited to, war, civil unrest, strikes, accident, incapacitating illness, fire, flood, travel disruption
- Dangerous and/or unsuitable conditions for the course being present or forecast

If the course is cancelled, LUMC will notify participants as soon as reasonably practicable. Where the course is cancelled by LUMC the participant (or a substitute colleague) can follow the same course at a later timepoint.
