---
title: "(Preliminary) Schedule"
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: process-schedule
#| echo: false
#| message: false
#| results: false
#| warning: false

library(kableExtra)
local_sys <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "English")

df_sched <- readxl::read_xlsx(here::here("asa-2024-schedule.xlsx"), sheet = 1)
df_sched$start_time <- format(as.POSIXct(df_sched$start_time), format = "%H:%M")
df_sched$finish_time <- format(as.POSIXct(df_sched$finish_time), format = "%H:%M")
df_sched$weekday <- weekdays(as.POSIXct(df_sched$date))
df_sched$date_short <- format(as.POSIXct(df_sched$date), format = "%d/%m")
df_sched$date_lab <- with(df_sched, paste0(weekday, " (", date_short, ")"))
df_sched[is.na(df_sched)] <- ""

# Set again
Sys.setlocale("LC_TIME", local_sys)
```

## Monday (26/08)

```{r}
#| label: schedule-mon
#| echo: false

df_sched[df_sched$weekday == "Monday", c(
  "start_time",
  "finish_time",
  "instructor",
  "topic",
  "session_code"
)] |> 
  kbl(col.names = c("Start", "Finish", "Instructor", "Session title", "Session code")) |> 
  kable_styling(c("striped", "hover")) |> 
  column_spec(1, width = "1cm") |> 
  column_spec(2, width = "1cm") |> 
  column_spec(3, width = "4cm") |> 
  column_spec(4, italic = TRUE, width = "8cm")
```

## Tuesday (27/08)

```{r}
#| label: schedule-tue
#| echo: false

df_sched[df_sched$weekday == "Tuesday", c(
  "start_time",
  "finish_time",
  "instructor",
  "topic",
  "session_code"
)] |> 
  kbl(col.names = c("Start", "Finish", "Instructor", "Session title", "Session code")) |> 
  kable_styling(c("striped", "hover")) |> 
  column_spec(1, width = "1cm") |> 
  column_spec(2, width = "1cm") |> 
  column_spec(3, width = "4cm") |> 
  column_spec(4, italic = TRUE, width = "8cm")
```

## Wednesday (28/08)

```{r}
#| label: schedule-wed
#| echo: false

df_sched[df_sched$weekday == "Wednesday", c(
  "start_time",
  "finish_time",
  "instructor",
  "topic",
  "session_code"
)] |> 
  kbl(col.names = c("Start", "Finish", "Instructor", "Session title", "Session code")) |> 
  kable_styling(c("striped", "hover")) |> 
  column_spec(1, width = "1cm") |> 
  column_spec(2, width = "1cm") |> 
  column_spec(3, width = "4cm") |> 
  column_spec(4, italic = TRUE, width = "8cm")
```

## Thursday (29/08)

```{r}
#| label: schedule-thu
#| echo: false

df_sched[df_sched$weekday == "Thursday", c(
  "start_time",
  "finish_time",
  "instructor",
  "topic",
  "session_code"
)] |> 
  kbl(col.names = c("Start", "Finish", "Instructor", "Session title", "Session code")) |> 
  kable_styling(c("striped", "hover")) |> 
  column_spec(1, width = "1cm") |> 
  column_spec(2, width = "1cm") |> 
  column_spec(3, width = "4cm") |> 
  column_spec(4, italic = TRUE, width = "8cm")
```

## Friday (30/08)

```{r}
#| label: schedule-fri
#| echo: false

df_sched[df_sched$weekday == "Friday", c(
  "start_time",
  "finish_time",
  "instructor",
  "topic",
  "session_code"
)] |> 
  kbl(col.names = c("Start", "Finish", "Instructor", "Session title", "Session code")) |> 
  kable_styling(c("striped", "hover")) |> 
  column_spec(1, width = "1cm") |> 
  column_spec(2, width = "1cm") |> 
  column_spec(3, width = "4cm") |> 
  column_spec(4, italic = TRUE, width = "8cm")
```
